[package]
name = "rds-failover"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.39"
sqlx = { version = "0.8.3", features = ["runtime-tokio", "postgres", "migrate"] }
tokio = { version = "1", features = ["full"] }
tracing = "0.1"
tracing-subscriber = "0.3"
